package workflows

import (
	"context"
	"fmt"

	"github.com/talos-platform/talos-platform/internal/application/ports"
	"github.com/talos-platform/talos-platform/internal/domain/cluster"
	"github.com/talos-platform/talos-platform/internal/domain/gitops"
	"github.com/talos-platform/talos-platform/internal/domain/workflow"
)

// changeBranch is stable per cluster and operation (not per workflow run),
// so a retried step targets the same branch instead of drifting apart — the
// same reasoning as provisionBranch, generalized to non-provisioning
// operations (upgrade, scale) that also need to commit a change.
func changeBranch(c *cluster.Cluster, operation string) string {
	return fmt.Sprintf("platform/cluster-%s-%s", c.Name, operation)
}

// commitClusterAPIChange renders and commits the current desired state for
// a CLUSTER_API-mode cluster and opens a PR for it — the only way a
// CLUSTER_API-mode cluster's desired state reaches its controllers
// (ADR-0002: the platform generates/updates CAPI manifests, commits to Git,
// and never reconciles CAPI resources itself) — the counterpart to how
// DIRECT_TALOS-mode upgrade/scale steps call ports.TalosClient directly
// instead. It does not merge the PR or wait for Argo CD/Cluster API — see
// awaitClusterAPIChangeMerge, a separate step so a retry (e.g. after
// Engine.Resume) re-checks merge status instead of re-committing and
// re-opening a duplicate PR.
//
// No-op (returns nil immediately) for DIRECT_TALOS-mode clusters, so
// callers can invoke it unconditionally from a workflow step.
func commitClusterAPIChange(ctx context.Context, deps ClusterProvisionDeps, c *cluster.Cluster, wf *workflow.Workflow, operation, description string) error {
	if c.ProviderMode != cluster.ProviderModeClusterAPI {
		return nil
	}

	repo, err := gitOpsRepo(ctx, deps, c.ID)
	if err != nil {
		return err
	}
	files, err := renderManifestSet(ctx, deps, c, repo)
	if err != nil {
		return fmt.Errorf("rendering manifests: %w", err)
	}

	branch := changeBranch(c, operation)
	if err := deps.Git.CreateBranch(ctx, repo.owner, repo.name, branch, repo.defaultBranch); err != nil {
		return fmt.Errorf("creating branch: %w", err)
	}
	result, err := deps.Git.Commit(ctx, ports.CommitRequest{
		Owner: repo.owner, Repo: repo.name, Branch: branch, Message: description, Files: files,
	})
	if err != nil {
		return fmt.Errorf("committing manifests: %w", err)
	}

	changeset := &gitops.ChangeSet{
		ClusterID: c.ID, WorkflowID: &wf.ID, Description: description,
		GeneratedFiles: filePaths(files), CommitSHA: result.SHA,
		Status: gitops.ChangeSetCommitted,
	}
	if err := deps.GitOps.CreateChangeSet(ctx, changeset); err != nil {
		return fmt.Errorf("recording change set: %w", err)
	}

	pr, err := deps.Git.CreatePullRequest(ctx, ports.PullRequestRequest{
		Owner: repo.owner, Repo: repo.name, Title: description,
		Body: "Generated by the Talos Platform " + operation + " workflow.",
		Head: branch, Base: repo.defaultBranch,
	})
	if err != nil {
		return fmt.Errorf("creating pull request: %w", err)
	}
	changeset.PullRequestURL = pr.URL
	changeset.Status = gitops.ChangeSetPRCreated
	if err := deps.GitOps.UpdateChangeSet(ctx, changeset); err != nil {
		return fmt.Errorf("recording change set: %w", err)
	}
	return nil
}

// awaitClusterAPIChangeMerge is the §4 human-in-the-loop gate counterpart to
// commitClusterAPIChange: it checks whether the PR that opened has been
// merged yet, and if not, returns ErrAwaitingApproval so the engine pauses
// this workflow until a GitHub PR-merged webhook (webhook_handlers.go)
// resumes it. Once merged, it triggers an Argo CD sync (if enabled) and
// records the change set as synced. No-op for DIRECT_TALOS-mode clusters.
func awaitClusterAPIChangeMerge(ctx context.Context, deps ClusterProvisionDeps, c *cluster.Cluster) error {
	if c.ProviderMode != cluster.ProviderModeClusterAPI {
		return nil
	}

	changeset, err := latestChangeSet(ctx, deps, c.ID)
	if err != nil {
		return err
	}
	repo, err := gitOpsRepo(ctx, deps, c.ID)
	if err != nil {
		return err
	}
	prNumber, err := prNumberFromURL(changeset.PullRequestURL)
	if err != nil {
		return err
	}
	pr, err := deps.Git.GetPullRequest(ctx, repo.owner, repo.name, prNumber)
	if err != nil {
		return fmt.Errorf("checking pull request #%d: %w", prNumber, err)
	}
	if pr.State != "merged" {
		return ErrAwaitingApproval
	}
	changeset.Status = gitops.ChangeSetMerged
	changeset.Result = "merged"
	if err := deps.GitOps.UpdateChangeSet(ctx, changeset); err != nil {
		return fmt.Errorf("recording merged change set: %w", err)
	}

	if c.Spec.ArgoCD.Enabled {
		if err := deps.ArgoCD.Sync(ctx, c.Name); err != nil {
			return fmt.Errorf("syncing argocd application: %w", err)
		}
		changeset.Status = gitops.ChangeSetSynced
		if err := deps.GitOps.UpdateChangeSet(ctx, changeset); err != nil {
			return fmt.Errorf("recording synced change set: %w", err)
		}
	}

	return nil
}

// waitForClusterAPIReady polls (once, per step-execution semantics — a
// retried step re-checks rather than blocking) Cluster API's observed
// status for c and fails the step if any resource isn't ready yet. No-op
// for DIRECT_TALOS-mode clusters.
func waitForClusterAPIReady(ctx context.Context, deps ClusterProvisionDeps, c *cluster.Cluster) error {
	if c.ProviderMode != cluster.ProviderModeClusterAPI {
		return nil
	}
	statuses, err := deps.ClusterAPI.GetClusterStatus(ctx, "default", c.Name)
	if err != nil {
		return fmt.Errorf("checking CAPI status: %w", err)
	}
	for _, s := range statuses {
		if !s.Ready {
			return fmt.Errorf("CAPI resource %s/%s not ready (phase=%s)", s.Kind, s.Name, s.Phase)
		}
	}
	return nil
}
