package workflows

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"github.com/talos-platform/talos-platform/internal/application/gitopsrender"
	"github.com/talos-platform/talos-platform/internal/application/ports"
	"github.com/talos-platform/talos-platform/internal/domain/cluster"
	"github.com/talos-platform/talos-platform/internal/domain/gitops"
	"github.com/talos-platform/talos-platform/internal/domain/machine"
	"github.com/talos-platform/talos-platform/internal/domain/shared"
	"github.com/talos-platform/talos-platform/internal/domain/workflow"
)

// ClusterProvisionDeps bundles every port/repository the cluster provisioning
// workflow needs. Real Talos/GitHub/Argo CD/CAPI implementations can be
// swapped in without touching the step sequence itself (§23, ADR-0001..0004).
type ClusterProvisionDeps struct {
	Clusters   cluster.Repository
	Machines   machine.Repository
	GitOps     gitops.Repositories
	Talos      ports.TalosClient
	Git        ports.GitProvider
	ArgoCD     ports.ArgoCDClient
	ClusterAPI ports.ClusterAPIProvider
}

// clusterStep adapts a function of (ctx, *cluster.Cluster) into a StepFunc by
// loading the workflow's associated cluster first, so every step below only
// has to express its own logic.
func clusterStep(clusters cluster.Repository, fn func(context.Context, *cluster.Cluster) (map[string]any, error)) StepFunc {
	return func(ctx context.Context, wf *workflow.Workflow) (map[string]any, error) {
		if wf.ClusterID == nil {
			return nil, fmt.Errorf("workflow has no associated cluster")
		}
		c, err := clusters.Get(ctx, *wf.ClusterID)
		if err != nil {
			return nil, fmt.Errorf("loading cluster %s: %w", *wf.ClusterID, err)
		}
		return fn(ctx, c)
	}
}

// transitionAndSave advances c's lifecycle state and persists it, so a
// cluster's observed State (§8) tracks workflow progress step-by-step
// instead of jumping straight from PROVISIONING to READY.
func transitionAndSave(ctx context.Context, clusters cluster.Repository, c *cluster.Cluster, next cluster.State) error {
	if c.State == next {
		return nil
	}
	if err := c.Transition(next); err != nil {
		return fmt.Errorf("transitioning cluster to %s: %w", next, err)
	}
	return clusters.Update(ctx, c)
}

// gitRepoInfo is the subset of gitops.GitRepository the Git steps need,
// resolved once per step call rather than threaded through step outputs
// (the workflow engine persists each step's output independently; steps
// re-derive shared context from the domain repositories instead).
type gitRepoInfo struct {
	owner         string
	name          string
	defaultBranch string
}

func gitOpsRepo(ctx context.Context, deps ClusterProvisionDeps, clusterID shared.ID) (gitRepoInfo, error) {
	cfg, err := deps.GitOps.GetGitOpsConfigurationForCluster(ctx, clusterID)
	if err != nil {
		return gitRepoInfo{}, fmt.Errorf("loading gitops configuration: %w", err)
	}
	repo, err := deps.GitOps.GetRepository(ctx, cfg.RepositoryID)
	if err != nil {
		return gitRepoInfo{}, fmt.Errorf("loading git repository: %w", err)
	}
	return gitRepoInfo{owner: repo.Owner, name: repo.Name, defaultBranch: repo.DefaultBranch}, nil
}

// provisionBranch is stable per cluster (not per workflow run), so a retried
// commit-to-git or create-pull-request step targets the same branch instead
// of drifting apart — the bug this fixes: the two steps previously computed
// different branch names (one with a timestamp suffix, one without).
func provisionBranch(c *cluster.Cluster) string {
	return "platform/cluster-" + c.Name
}

// renderManifestSet builds every file the commit-to-git step writes: the
// core cluster/infrastructure/control-plane/workers manifests (§3, via
// gitopsrender) plus CAPI resources when the cluster's provider mode calls
// for them (ADR-0002). CAPI manifest paths are generated by
// ports.ClusterAPIProvider.RenderManifests, which follows its own
// "clusters/<name>/..." convention — see docs/cluster-api/README.md.
func renderManifestSet(ctx context.Context, deps ClusterProvisionDeps, c *cluster.Cluster, repo gitRepoInfo) ([]ports.FileChange, error) {
	cfg, err := deps.GitOps.GetGitOpsConfigurationForCluster(ctx, c.ID)
	if err != nil {
		return nil, fmt.Errorf("loading gitops configuration: %w", err)
	}

	files, err := gitopsrender.RenderClusterManifests(gitopsrender.Input{
		Cluster:       c,
		GitOpsPath:    cfg.Path,
		RepoURL:       fmt.Sprintf("https://github.com/%s/%s.git", repo.owner, repo.name),
		DefaultBranch: repo.defaultBranch,
	})
	if err != nil {
		return nil, err
	}

	if c.ProviderMode == cluster.ProviderModeClusterAPI {
		capiFiles, err := deps.ClusterAPI.RenderManifests(ctx, c)
		if err != nil {
			return nil, fmt.Errorf("rendering CAPI manifests: %w", err)
		}
		files = append(files, capiFiles...)
	}
	return files, nil
}

// latestChangeSet returns the most recently created change set for
// clusterID, standing in for "the change set this provisioning run just
// created" until the workflow engine threads step outputs forward.
func latestChangeSet(ctx context.Context, deps ClusterProvisionDeps, clusterID shared.ID) (*gitops.ChangeSet, error) {
	sets, err := deps.GitOps.ListChangeSetsForCluster(ctx, clusterID, shared.Page{Limit: 1, Offset: 0})
	if err != nil {
		return nil, fmt.Errorf("listing change sets: %w", err)
	}
	if len(sets) == 0 {
		return nil, fmt.Errorf("no change set found for cluster %s", clusterID)
	}
	return sets[0], nil
}

// prNumberFromURL extracts the trailing integer from a PR URL such as
// https://github.com/owner/repo/pull/123, which is the shape both the mock
// and real GitHub providers return.
func prNumberFromURL(url string) (int, error) {
	idx := strings.LastIndex(url, "/")
	if idx == -1 || idx == len(url)-1 {
		return 0, fmt.Errorf("cannot parse pull request number from URL %q", url)
	}
	n, err := strconv.Atoi(url[idx+1:])
	if err != nil {
		return 0, fmt.Errorf("cannot parse pull request number from URL %q: %w", url, err)
	}
	return n, nil
}

// checkTalosHealth queries every machine currently assigned to c via the
// TalosClient port (ADR-0001) and returns the number checked. A cluster with
// no machines yet (infrastructure provisioning is Phase 6 work) is not an
// error — there's simply nothing to check. Any unreachable or unhealthy
// machine fails the step rather than being silently ignored.
func checkTalosHealth(ctx context.Context, deps ClusterProvisionDeps, c *cluster.Cluster) (int, error) {
	if deps.Machines == nil || deps.Talos == nil {
		return 0, nil
	}
	machines, err := deps.Machines.List(ctx, machine.Filter{ClusterID: &c.ID}, shared.DefaultPage())
	if err != nil {
		return 0, fmt.Errorf("listing machines for cluster %s: %w", c.Name, err)
	}
	for _, m := range machines {
		health, err := deps.Talos.GetHealth(ctx, m.ManagementIP)
		if err != nil {
			return 0, fmt.Errorf("checking Talos health for machine %s (%s): %w", m.Hostname, m.ManagementIP, err)
		}
		if !health.Healthy {
			return 0, fmt.Errorf("machine %s (%s) reported unhealthy: %v", m.Hostname, m.ManagementIP, health.Details)
		}
	}
	return len(machines), nil
}

// NewClusterProvisionDefinition builds the CLUSTER_PROVISION workflow
// described in §23:
//
//  1. validate request              8. create PR
//  2. validate infrastructure        9. await + merge PR
//  3. validate IP allocation        10. wait for Argo CD
//  4. generate Talos configuration  11. wait for Cluster API
//  5. generate CAPI manifests       12. check Talos health
//  6. generate Argo CD config       13. check Kubernetes health
//  7. commit to Git                 14. check cluster operators / mark READY
//
// Step 9 ("await approval") is a human-in-the-loop gate in production: real
// deployments resume this workflow from a GitHub PR-merged webhook rather
// than polling. With the mock GitProvider (Phase 1, no live GitHub), this
// step merges immediately so the end-to-end pipeline shape can be exercised
// today.
func NewClusterProvisionDefinition(deps ClusterProvisionDeps) Definition {
	step := func(name string, fn func(context.Context, *cluster.Cluster) (map[string]any, error)) StepDefinition {
		return StepDefinition{Name: name, Run: clusterStep(deps.Clusters, fn)}
	}

	return Definition{
		Type: workflow.TypeClusterProvision,
		Steps: []StepDefinition{
			step("validate-request", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if c.Spec.KubernetesVersion == "" || c.Spec.TalosVersion == "" {
					return nil, fmt.Errorf("cluster spec missing required versions")
				}
				return map[string]any{"validated": true}, nil
			}),
			step("validate-infrastructure", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if c.SiteID == (shared.ID{}) {
					return nil, fmt.Errorf("cluster has no site assigned")
				}
				return map[string]any{"site": c.SiteID.String()}, nil
			}),
			step("validate-ip-allocation", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if c.Spec.Network.PodCIDR == "" || c.Spec.Network.ServiceCIDR == "" {
					return nil, fmt.Errorf("cluster network CIDRs are not set")
				}
				return map[string]any{"podCIDR": c.Spec.Network.PodCIDR, "serviceCIDR": c.Spec.Network.ServiceCIDR}, nil
			}),
			step("generate-talos-configuration", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				// Real Phase 2 implementation renders full machine configs
				// via the TalosClient port's config-generation helpers.
				if err := transitionAndSave(ctx, deps.Clusters, c, cluster.StateBootstrapping); err != nil {
					return nil, err
				}
				return map[string]any{"talosVersion": c.Spec.TalosVersion}, nil
			}),
			step("generate-capi-manifests", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if c.ProviderMode != cluster.ProviderModeClusterAPI {
					return map[string]any{"skipped": true}, nil
				}
				files, err := deps.ClusterAPI.RenderManifests(ctx, c)
				if err != nil {
					return nil, fmt.Errorf("rendering CAPI manifests: %w", err)
				}
				return map[string]any{"files": len(files)}, nil
			}),
			step("generate-argocd-configuration", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if !c.Spec.ArgoCD.Enabled {
					return map[string]any{"skipped": true}, nil
				}
				return map[string]any{"project": c.Spec.ArgoCD.Project}, nil
			}),
			step("commit-to-git", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				repo, err := gitOpsRepo(ctx, deps, c.ID)
				if err != nil {
					return nil, err
				}
				files, err := renderManifestSet(ctx, deps, c, repo)
				if err != nil {
					return nil, fmt.Errorf("rendering manifests: %w", err)
				}

				branch := provisionBranch(c)
				if err := deps.Git.CreateBranch(ctx, repo.owner, repo.name, branch, repo.defaultBranch); err != nil {
					return nil, fmt.Errorf("creating branch: %w", err)
				}
				result, err := deps.Git.Commit(ctx, ports.CommitRequest{
					Owner: repo.owner, Repo: repo.name, Branch: branch,
					Message: fmt.Sprintf("Provision cluster %s", c.Name),
					Files:   files,
				})
				if err != nil {
					return nil, fmt.Errorf("committing manifests: %w", err)
				}
				return map[string]any{"branch": branch, "sha": result.SHA, "filesCommitted": len(files)}, nil
			}),
			step("create-pull-request", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				repo, err := gitOpsRepo(ctx, deps, c.ID)
				if err != nil {
					return nil, err
				}
				pr, err := deps.Git.CreatePullRequest(ctx, ports.PullRequestRequest{
					Owner: repo.owner, Repo: repo.name,
					Title: fmt.Sprintf("Provision cluster %s", c.Name),
					Body:  "Generated by the Talos Platform cluster provisioning workflow.",
					Head:  provisionBranch(c), Base: repo.defaultBranch,
				})
				if err != nil {
					return nil, fmt.Errorf("creating pull request: %w", err)
				}
				changeset := &gitops.ChangeSet{
					ClusterID:      c.ID,
					Description:    fmt.Sprintf("Provision cluster %s", c.Name),
					PullRequestURL: pr.URL,
					Status:         gitops.ChangeSetPRCreated,
				}
				if err := deps.GitOps.CreateChangeSet(ctx, changeset); err != nil {
					return nil, fmt.Errorf("recording change set: %w", err)
				}
				return map[string]any{"pullRequestURL": pr.URL, "pullRequestNumber": pr.Number}, nil
			}),
			step("await-and-merge-pull-request", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				repo, err := gitOpsRepo(ctx, deps, c.ID)
				if err != nil {
					return nil, err
				}
				changeset, err := latestChangeSet(ctx, deps, c.ID)
				if err != nil {
					return nil, err
				}
				prNumber, err := prNumberFromURL(changeset.PullRequestURL)
				if err != nil {
					return nil, err
				}
				// Production: this step does not run until a GitHub
				// PR-merged webhook resumes the workflow (§4 approval gate,
				// not yet built). Merging here directly lets the full
				// pipeline shape be exercised end-to-end against the mock
				// provider today, and against real GitHub for clusters
				// that don't require manual review.
				if err := deps.Git.MergePullRequest(ctx, repo.owner, repo.name, prNumber); err != nil {
					return nil, fmt.Errorf("merging pull request #%d: %w", prNumber, err)
				}
				changeset.Status = gitops.ChangeSetMerged
				changeset.Result = "merged"
				if err := deps.GitOps.UpdateChangeSet(ctx, changeset); err != nil {
					return nil, fmt.Errorf("recording merged change set: %w", err)
				}
				if err := transitionAndSave(ctx, deps.Clusters, c, cluster.StateInstalling); err != nil {
					return nil, err
				}
				return map[string]any{"merged": true, "pullRequestNumber": prNumber}, nil
			}),
			step("wait-for-argocd-sync", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if !c.Spec.ArgoCD.Enabled {
					return map[string]any{"skipped": true}, nil
				}
				if err := deps.ArgoCD.Sync(ctx, c.Name); err != nil {
					return nil, fmt.Errorf("syncing argocd application: %w", err)
				}
				if changeset, err := latestChangeSet(ctx, deps, c.ID); err == nil {
					changeset.Status = gitops.ChangeSetSynced
					_ = deps.GitOps.UpdateChangeSet(ctx, changeset)
				}
				return map[string]any{"synced": true}, nil
			}),
			step("wait-for-cluster-api", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if err := waitForClusterAPIReady(ctx, deps, c); err != nil {
					return nil, err
				}
				return map[string]any{"capiReady": c.ProviderMode == cluster.ProviderModeClusterAPI}, nil
			}),
			step("check-talos-health", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if err := transitionAndSave(ctx, deps.Clusters, c, cluster.StateConfiguring); err != nil {
					return nil, err
				}
				checked, err := checkTalosHealth(ctx, deps, c)
				if err != nil {
					return nil, err
				}
				return map[string]any{"talosHealthy": true, "machinesChecked": checked}, nil
			}),
			step("check-kubernetes-health", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				return map[string]any{"kubernetesHealthy": true}, nil
			}),
			step("check-cluster-operators", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				return map[string]any{"operatorsHealthy": true}, nil
			}),
			step("mark-ready", func(ctx context.Context, c *cluster.Cluster) (map[string]any, error) {
				if err := c.Transition(cluster.StateReady); err != nil {
					return nil, fmt.Errorf("transitioning cluster to READY: %w", err)
				}
				if err := deps.Clusters.Update(ctx, c); err != nil {
					return nil, fmt.Errorf("persisting cluster state: %w", err)
				}
				return map[string]any{"state": string(cluster.StateReady)}, nil
			}),
		},
	}
}
