apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "platform.fullname" . }}-config
  labels:
    {{- include "platform.labels" . | nindent 4 }}
data:
  PLATFORM_ENV: {{ .Values.config.env | quote }}
  PLATFORM_AUTH_MODE: {{ .Values.config.authMode | quote }}
  PLATFORM_TALOS_ADAPTER: {{ .Values.config.talosAdapter | quote }}
  PLATFORM_GITHUB_ADAPTER: {{ .Values.config.githubAdapter | quote }}
  PLATFORM_ARGOCD_ADAPTER: {{ .Values.config.argocdAdapter | quote }}
  PLATFORM_CLUSTERAPI_ADAPTER: {{ .Values.config.clusterapiAdapter | quote }}
  PLATFORM_PROXMOX_ADAPTER: {{ .Values.config.proxmoxAdapter | quote }}
  PLATFORM_SECRETSTORE_BACKEND: {{ .Values.config.secretStoreBackend | quote }}
  PLATFORM_TRACING_ENABLED: {{ .Values.config.tracingEnabled | quote }}
  PLATFORM_OTLP_ENDPOINT: {{ .Values.config.otlpEndpoint | quote }}
